IMAGE_SIZE = 640
CHESSBOARD_BORDER = 46
CHESSBOARD_START = CHESSBOARD_BORDER
CHESSBOARD_END = IMAGE_SIZE - CHESSBOARD_BORDER
CHESSBOARD_SQUARE = round((IMAGE_SIZE - CHESSBOARD_BORDER * 2) / 8)
CHESSBOARD_SQUARE_BORDER = round(CHESSBOARD_SQUARE * 0.25)
